import { Difficulty } from './difficulty';
import { Square } from './square';

export const MOCKSQUARES: Square[] = [
  {
    id: 1,
    value: 'Acquire Mythic Weapon',
    difficulty: Difficulty.Medium,
  },
  { id: 2, value: 'Attacked by Bruce', difficulty: Difficulty.Medium },
  { id: 3, value: 'Attacked by an NPC', difficulty: Difficulty.Hard },
  { id: 4, value: 'Be on the Loot Boat', difficulty: Difficulty.Hard },
  { id: 5, value: 'Bounce off Shrooms', difficulty: Difficulty.Easy },
  { id: 6, value: 'Bounce on a Spider Web', difficulty: Difficulty.Hard },
  { id: 7, value: 'Bounty Poached', difficulty: Difficulty.Medium },
  { id: 8, value: 'Buy from Vending Machine', difficulty: Difficulty.Easy },
  { id: 9, value: 'Catch Something On Fire', difficulty: Difficulty.Medium },
  { id: 10, value: 'Catch a Fish While Fishing', difficulty: Difficulty.Easy },
  {
    id: 11,
    value: 'Catch a Weapon While Fishing',
    difficulty: Difficulty.Easy,
  },
  {
    id: 12,
    value: 'Center of Third Circle is Northeast',
    group: 'Third Circle',
    difficulty: Difficulty.Easy,
  },
  {
    id: 13,
    value: 'Center of Third Circle is Northwest',
    group: 'Third Circle',
    difficulty: Difficulty.Easy,
  },
  {
    id: 14,
    value: 'Center of Third Circle is Southeast',
    group: 'Third Circle',
    difficulty: Difficulty.Easy,
  },
  {
    id: 15,
    value: 'Center of Third Circle is Southwest',
    group: 'Third Circle',
    difficulty: Difficulty.Easy,
  },
  {
    id: 16,
    value: 'Damage Enemy With Log or Boulder',
    difficulty: Difficulty.Hard,
  },
  {
    id: 17,
    value: 'Damage Player while Sliding',
    difficulty: Difficulty.Hard,
  },
  { id: 18, value: 'Destroy a Reality Sapling', difficulty: Difficulty.Medium },
  { id: 19, value: 'Dies In Storm', difficulty: Difficulty.Hard },
  {
    id: 20,
    value: 'Eat Food (Fish} fruit} veggies)',
    difficulty: Difficulty.Easy,
  },
  {
    id: 21,
    value: 'Emotes Immediately After New Spectator',
    difficulty: Difficulty.Medium,
  },
  {
    id: 22,
    value: 'First Aid Kit / Bandages From Big Ammo Crate',
    difficulty: Difficulty.Medium,
  },
  {
    id: 23,
    value: 'First Zone Pulls Max Distance',
    difficulty: Difficulty.Medium,
  },
  {
    id: 24,
    value: 'Get in Vehicle - Radio is OFF',
    difficulty: Difficulty.Easy,
  },
  {
    id: 25,
    value: 'Get in Vehicle - Radio is ON',
    difficulty: Difficulty.Easy,
  },
  {
    id: 26,
    value: 'Gold Weapon From Regular Chest',
    difficulty: Difficulty.Hard,
  },
  { id: 27, value: 'Grey Weapon Elimination', difficulty: Difficulty.Medium },
  {
    id: 28,
    value: 'Hit a Player With a Vehicle',
    difficulty: Difficulty.Medium,
  },
  { id: 29, value: 'Interacts With NPC', difficulty: Difficulty.Easy },
  { id: 30, value: 'Kill Llama', difficulty: Difficulty.Medium },
  {
    id: 31,
    value: 'Kill Non-Weapon Dropping Wildlife',
    difficulty: Difficulty.Easy,
  },
  {
    id: 32,
    value: 'Damage Player with Explosives',
    difficulty: Difficulty.Hard,
  },
  {
    id: 33,
    value: 'Kill Player with Melee Weapon',
    difficulty: Difficulty.Hard,
  },
  { id: 34, value: 'Kill Player with Shotgun', difficulty: Difficulty.Easy },
  { id: 35, value: 'Kill Player with Sniper', difficulty: Difficulty.Medium },
  {
    id: 36,
    value: 'Kill With Less Than 10HP Left',
    difficulty: Difficulty.Medium,
  },
  { id: 37, value: 'Kill a Player in the Air', difficulty: Difficulty.Hard },
  {
    id: 38,
    value: 'Kill a Purple or Gold Bird',
    difficulty: Difficulty.Easy,
  },
  {
    id: 39,
    value: 'Kill or be Killed While in Vehicle',
    difficulty: Difficulty.Hard,
  },
  {
    id: 40,
    value: 'Kill the Bounty or Avoid Being the Bounty',
    difficulty: Difficulty.Hard,
  },
  { id: 41, value: 'Knock Down a Boulder', difficulty: Difficulty.Easy },
  { id: 42, value: 'Knock Down a Logging Tree', difficulty: Difficulty.Easy },
  { id: 43, value: 'Koooooom Dies Top 10', difficulty: Difficulty.Easy },
  { id: 44, value: 'Land at named POI', difficulty: Difficulty.Easy },
  { id: 45, value: 'Launches From Geyser', difficulty: Difficulty.Easy },
  {
    id: 46,
    value: 'Leave First POI without Max Health/Shield',
    difficulty: Difficulty.Medium,
  },
  { id: 47, value: 'Level Up', difficulty: Difficulty.Easy },
  { id: 48, value: 'Light a Campfire', difficulty: Difficulty.Easy },
  {
    id: 49,
    value: 'Mount Gets Killed or Sleeps',
    difficulty: Difficulty.Medium,
  },
  { id: 50, value: 'Open Epic Blue Chest', difficulty: Difficulty.Medium },
  { id: 51, value: 'Open IO/7/SW Special Chest', difficulty: Difficulty.Easy },
  { id: 52, value: 'Open a Buried Chest', difficulty: Difficulty.Hard },
  { id: 53, value: 'Open a Cooler', difficulty: Difficulty.Easy },
  { id: 54, value: 'Open a Safe', difficulty: Difficulty.Medium },
  { id: 55, value: 'Open a Supply Drop', difficulty: Difficulty.Medium },
  {
    id: 56,
    value: 'Pick Fruit From a Reality Sapling',
    difficulty: Difficulty.Easy,
  },
  { id: 57, value: 'Pick Up A Crown', difficulty: Difficulty.Medium },
  { id: 58, value: 'Purchase from NPC', difficulty: Difficulty.Medium },
  {
    id: 59,
    value: 'Repair a Vehicle',
    difficulty: Difficulty.Medium,
    disabled: true,
  },
  {
    id: 60,
    value: 'Ride Updraft on Reality Falls Tree',
    difficulty: Difficulty.Medium,
  },
  { id: 61, value: 'Ride a Boar or Wolf', difficulty: Difficulty.Easy },
  {
    id: 62,
    value: 'Ride the Foundation Statue Updraft',
    difficulty: Difficulty.Medium,
  },
  { id: 63, value: 'Ride the Rollercoaster', difficulty: Difficulty.Hard },
  { id: 64, value: 'Ride the Slipstream', difficulty: Difficulty.Easy },
  {
    id: 65,
    value: 'Run Out of Ammo After First Fight',
    difficulty: Difficulty.Hard,
  },
  { id: 66, value: 'Shields From Big Ammo Crate', difficulty: Difficulty.Easy },
  { id: 67, value: 'Shoots Enemy Vehicle', difficulty: Difficulty.Medium },
  { id: 68, value: 'Solid Gold+ Weapon Loadout', difficulty: Difficulty.Hard },
  { id: 69, value: 'Take Fall Damage', difficulty: Difficulty.Medium },
  { id: 70, value: 'Take a Rift', difficulty: Difficulty.Easy },
  { id: 71, value: 'Tires from Toolbox', difficulty: Difficulty.Easy },
  { id: 72, value: 'Upgrade A Vehicle', difficulty: Difficulty.Easy },
  { id: 73, value: 'Upgrade a Weapon', difficulty: Difficulty.Hard },
  { id: 74, value: 'Use A Vertical Zipline', difficulty: Difficulty.Medium },
  { id: 75, value: 'Use Grappler Glove', difficulty: Difficulty.Easy },
  { id: 76, value: 'Use Med Mist', difficulty: Difficulty.Medium },
  { id: 77, value: 'Use Ripsaw Launcher', difficulty: Difficulty.Medium },
  { id: 78, value: 'Use a Baller', difficulty: Difficulty.Hard },
  {
    id: 89,
    value: 'Use a Repair Torch (Burn or Repair)',
    difficulty: Difficulty.Easy,
    disabled: true,
  },
  {
    id: 80,
    value: 'Visit a Reality Zone: Coliseum',
    group: 'Reality Zone',
    difficulty: Difficulty.Easy,
  },
  {
    id: 81,
    value: 'Visit a Reality Zone: Coral',
    group: 'Reality Zone',
    difficulty: Difficulty.Easy,
  },
  {
    id: 82,
    value: 'Visit a Reality Zone: Neo',
    group: 'Reality Zone',
    difficulty: Difficulty.Easy,
  },
  {
    id: 83,
    value: 'Visit a Reality Zone: Pirate Cove/Wild West',
    group: 'Reality Zone',
    difficulty: Difficulty.Easy,
  },
  {
    id: 84,
    value: 'Visit a Reality Zone: Wild West',
    group: 'Reality Zone',
    difficulty: Difficulty.Easy,
    disabled: true,
  },
  { id: 85, value: 'Visits a Vault Building', difficulty: Difficulty.Medium },
  {
    id: 86,
    value: 'Witnesses Take the L or Laugh It Up',
    difficulty: Difficulty.Hard,
  },
  { id: 87, value: 'Complete Weekly Challenge', difficulty: Difficulty.Medium },
  { id: 88, value: 'Make Opponent Boogie', difficulty: Difficulty.Medium },
  {
    id: 89,
    value: 'Use Crash Pad',
    difficulty: Difficulty.Medium,
  },
  {
    id: 90,
    value: 'Experience  a Fortnite Bug',
    difficulty: Difficulty.Meme,
  },
  {
    id: 91,
    value: 'Stick to Opponent with Baller',
    difficulty: Difficulty.Meme,
    disabled: true,
  },
  {
    id: 92,
    value: 'Shockwave Opponent into Storm ',
    difficulty: Difficulty.Hard,
  },
  { id: 93, value: 'Complete Daily Challenge', difficulty: Difficulty.Medium },
];
